# Docker Compose for Alphanumeric Character Recognition
version: '3.8'

services:
  character-recognition:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Mount images folder for persistent storage
      - ./images:/app/images
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
